name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Show dotnet info
        run: dotnet --info

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj', '**/Directory.Packages.props', '**/global.json', '**/nuget.config') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore
        run: dotnet restore --nologo

      - name: Build (Release)
        run: dotnet build --configuration Release --nologo -warnaserror

      - name: Test (Release)
        run: dotnet test --configuration Release --nologo --no-build

      - name: pack (nupkg + snupkg, prerelease)
        run: dotnet pack src/NuExt.System.Data.SQLite.csproj -c Release -o artifacts --nologo /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg -p:VersionSuffix="pre.${{ github.run_number }}"

      - name: upload nupkg
        uses: actions/upload-artifact@v7
        with:
          name: nuext-system-data-sqlite-nupkg
          path: artifacts/*.nupkg

      - name: upload snupkg
        uses: actions/upload-artifact@v7
        with:
          name: nuext-system-data-sqlite-snupkg
          path: artifacts/*.snupkg